services:
  loan:
    image: "vikramb33/loans:0.0.1"
    container_name: loans_ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banknetwork
networks:
  banknetwork:
    driver: "bridge"